Data Cleaning - Aggregated Zillow Rent Data

# Introduction

In the following notebook, I will be cleaning an aggregation of the median rent prices across the United States from Zillow. This data pertains to 03/2010 through 11/2019.

Data will be used to supplement my analysis of the prices of different Airbnb listings in San Francisco.

* The aggregation source code [here](https://github.com/KishenSharma6/Airbnb-Analysis/blob/master/Project%20Codes/01.%20Raw%20Data%20Aggregation%20Scripts/2020_0129_Zillow_Raw_Data_Aggregation.ipynb)

* Raw data can be found [here](https://github.com/KishenSharma6/Airbnb-Analysis/tree/master/Data/01_Raw/Zillow%20Raw%20Data)

## Read in libraries,  read in data, and set notebook preferences

**Read in libraries**

In [28]:
#Read in libraries
import pandas as pd
import numpy as np

**Read in Data**

In [29]:
#Set path to Zillow Data
path = r'C:\Users\kishe\Documents\Data Science\Projects\Python Projects\In Progress\Air BnB - SF\Data\01_Raw\Zillow Raw Data\Zillow Raw Data Aggregated\12_29_2019_Zillow_Raw_Aggregated.csv'

#Read in Zillow data
zillow = pd.read_csv(path,index_col=0, dtype= {'Bedrooms':'object','SizeRank':'object','RegionName':'object'})

#Set new column order
new_columns =['City', 'CountyName', 'Metro', 'RegionName', 'State', 'SizeRank', 'Bedrooms'] + (zillow.columns.drop(cols_to_order).tolist())

#Update zillow
zillow = zillow[new_columns]

#Rename some columns for clarity
zillow = zillow.rename(columns= {'CountyName':'County',
                                'RegionName':'Zip'})

**Settings for Notebook**

In [30]:
#Set Pandas options
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows',500)
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [31]:
zillow.loc[:,'2010-03':]

,2010-03,2010-04,2010-05,2010-06,2010-07,2010-08,2010-09,2010-10,2010-11,2010-12,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12,2012-01,2012-02,2012-03,2012-04,2012-05,2012-06,2012-07,2012-08,2012-09,2012-10,2012-11,2012-12,2013-01,2013-02,2013-03,2013-04,2013-05,2013-06,2013-07,2013-08,2013-09,2013-10,2013-11,2013-12,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11
0,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1775.00,1795.00,1795.00,1850.00,1900.00,2000.00,1900.00,1900.00,1900.00,1895.00,1900.00,1875.00,1900.00,1900.00,1900.00,1925.00,2000.00,2072.50,2100.00,2150.00,2095.00,2000.00,2100.00,2150.00,2100.00,2190.00,2100.00,1995.00,2100.00,2200.00,2200.00,2290.00,2300.00,2300.00,2250.00,2250.00,2250.00,2300.00,2250.00,2450.00,2325.00,2400.00,2351.00,2400.00,2500.00,2401.50,2400.00,2505.00,2530.00,2530.00,2625.00,2500.00,2600.00,2650.00,2702.50,2727.50,2650.00,2600.00,2637.50,2702.50,2650.00,2613.00,2600.00,2510.00,2400.00,2591.50,2600.00,2550.00,2400.00,2500.00,2500.00,2600.00,2600.00,2595.00,2550.00,2505.00,2543.00,2550.00,2500.00,2500.00,2600.00,2600.00,2650.00,2700.00,2650.00,2665.00,2703.00,2682.00,2500.00,2406.50,2400.00,2600.00,2650.00,2700.00,2685.50,2700.00,2622.50,2700.00,2700.00,2800.00,2700.00,2700.00,2795.00,2869.50
1,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,895.00,850.00,845.00,875.00,885.00,895.00,900.00,875.00,875.00,915.00,950.00,905.00,950.00,950.00,925.00,925.00,925.00,925.00,950.00,985.00,985.00,985.00,975.00,980.00,975.00,995.00,975.00,960.00,977.50,975.00,975.00,975.00,965.00,1020.00,1000.00,995.00,1050.00,1050.00,1010.00,1005.00,1020.00,1020.00,1022.50,998.00,1075.00,1075.00,1050.00,1080.00,1095.00,1095.00,1125.00,1115.00,1095.00,1075.00,1075.00,1055.00,1070.00,1075.00,1075.00,1070.00,1150.00,1150.00,1150.00,1122.50,1150.00,1140.00,1130.00,1107.00,1100.00,1095.00,1095.00,1085.00,1150.00,1150.00,1145.00,1140.00,1142.50,1145.00,1125.00,1095.00,1050.00,1050.00,1030.00,1055.00,1127.50,1100.00,1195.00,1195.00,1165.00,1145.00,1150.00,1171.50,1150.00,1125.00,1120.00
2,nan,nan,nan,nan,nan,nan,nan,nan,nan,3400.00,2897.50,2447.50,2350.00,2350.00,2400.00,2500.00,2397.50,2350.00,2400.00,2300.00,2295.00,2200.00,2295.00,2295.00,2200.00,2235.00,2250.00,2240.00,2280.00,2299.00,2300.00,2350.00,2322.50,2300.00,2250.00,2200.00,2200.00,2210.00,2220.00,2300.00,2240.00,2270.00,2350.00,2300.00,2300.00,2365.00,2350.00,2395.00,2385.00,2330.00,2300.00,2400.00,2650.00,2675.00,2750.00,2800.00,2700.00,2700.00,2765.00,2750.00,2800.00,2875.00,2925.00,2900.00,2825.00,2768.00,2905.00,2897.50,2910.00,2850.00,2896.50,2900.00,2900.00,2884.00,2750.00,2720.00,2850.00,2652.00,2615.00,2695.00,2662.50,2600.00,2800.00,2850.00,2800.00,2800.00,2800.00,2750.00,2819.00,2760.00,2750.00,2765.00,2795.00,2800.00,2893.00,2897.50,2800.00,2800.00,2872.50,2800.00,2795.00,2700.00,2700.00,2790.00,2762.50,2787.50,2750.00,2800.00,2780.00,2800.00,2862.50,2700.00,2700.00,2755.00,2800.00,2800.00,2850.00
3,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1550.00,1527.50,1550.00,1527.50,1275.00,1350.00,1325.00,1397.50,1265.00,1340.00,1427.50,1500.00,1500.00,1467.00,1468.50,1469.00,1350.00,1300.00,1275.00,1250.00,1242.50,1205.00,1320.00,1300.00,1352.50,1347.50,1400.00,1390.00,1350.00,1345.00,1255.00,1250.00,1303.50,1360.00,1395.00,1405.00,1457.50,1450.00,1445.00,1399.00,1350.00,1342.00,1295.00,1295.00,1250.00,1255.00,1255.00,1285.00,1250.00,1285.00,1375.00,1300.00,1395.00,1361.00,1350.00,1320.00,1325.00,1325.00,1350.00,1320.00,1350.00
4,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1000.00,995.00,962.50,950.00,995.00,1000.00,1075.00,1037.50,1050.00,1050.00,995.00,1050.00,1075.00,1025.00,1000.00,1000.00,1000.00,995.00,985.00,985.00,975.00,975.00,950.00,950.00,967.50,960.00,950.00,950.00,950.00,995.00,975.00,975.00,950.00,950.00,995.00,995.00,995.00,1000.00,995.00,975.00,995.00,975.00,950.00,950.00,950.00,975.00,995.00,1000.00,1000.00,1012.50,1000.00,1000.00,1000.00,995.00,1000.00,995.00,1000.00,1000.00,975.00,995.00,950.00,982.50,975.00,985.00,975.00,975.00,975.00,970.00,1000.00,995.00,995.00,995.00,995.00,995.00,975.00,995.00,985.00,995.00,995.00,995.00,1050.00,1035.00,1050.00,1045.00,1000.00,1050.00,1050.00,1050.00,1050.00,1050.00,1000.00,995.00,1012.50,1000.00,1070.00,1100.00,1100.00,1100.00,1100.00,1085.00,1050.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1589,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,4650.00,5050.00,5100.00,5250.00,5300.00,5500.00,5500.00,5500.00,5500.00,5500.00,5875.00,5500.00,5000.00,5250.00,5500.00,5650.00,5500.00,5500.00,5650.00,5800.00,5850.00,6000.00,6000.00,5500.00,5500.00,5500.00,5800.00,5900.00,5625.00,6000.00,6000.00
1590,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1050.00,1050.00,1050.00,1050.00,1050.00,1050.00,1100.00,1095.00,1050.00,1050.00,1095.00,1100.00,1115.00,1095.00,1100.00,1100.00,1100.00,1100.00,1085.00
1591,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,20000.00,20000.00,20000.00,20000.00,20000.00,20000.00,20000.00,20000.00,20000.00,20000.00,20000.00,18000.00,20000.00,21000.00,20000.00,21000.00,21333.00,20500.00,20000.00,21000.00
1592,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,22250.00,22000.00,22000.00,21000.00,20000.00,20000.00,21000.00,20000.00,20000.00,22000.00,22000.00,23000.00,23000.00,22875.00,23000.00,22000.00,21166.50,20000.00,20000.00,18000.00
1593,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,40000.00,36000.00,35000.00,38000.00,35000.00,38000.00,39000.00,35000.00,36000.00,35000.00,40000.00,40000.00,39000.00,35000.00,36500.00,35000.00,32500.00,30000.00,31000.00,35000.00,30000.00,28500.00,30000.00,30000.00,29000.00,33750.00,30000.00,30000.00,28333.00,28333.00,28333.00,28333.00,28333.00,24500.00,28333.00,28333.00

## Data Preview

In [32]:
#Print shape of zillow data
print('Original zillow data shape:', zillow.shape)

#Preview zillow data
display(zillow.head())

Original zillow data shape: (6440, 124)

,City,County,Metro,Zip,State,SizeRank,Bedrooms,2010-03,2010-04,2010-05,2010-06,2010-07,2010-08,2010-09,2010-10,2010-11,2010-12,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12,2012-01,2012-02,2012-03,2012-04,2012-05,2012-06,2012-07,2012-08,2012-09,2012-10,2012-11,2012-12,2013-01,2013-02,2013-03,2013-04,2013-05,2013-06,2013-07,2013-08,2013-09,2013-10,2013-11,2013-12,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11
0,New York,New York County,New York-Newark-Jersey City,10025,NY,1,0,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1775.00,1795.00,1795.00,1850.00,1900.00,2000.00,1900.00,1900.00,1900.00,1895.00,1900.00,1875.00,1900.00,1900.00,1900.00,1925.00,2000.00,2072.50,2100.00,2150.00,2095.00,2000.00,2100.00,2150.00,2100.00,2190.00,2100.00,1995.00,2100.00,2200.00,2200.00,2290.00,2300.00,2300.00,2250.00,2250.00,2250.00,2300.00,2250.00,2450.00,2325.00,2400.00,2351.00,2400.00,2500.00,2401.50,2400.00,2505.00,2530.00,2530.00,2625.00,2500.00,2600.00,2650.00,2702.50,2727.50,2650.00,2600.00,2637.50,2702.50,2650.00,2613.00,2600.00,2510.00,2400.00,2591.50,2600.00,2550.00,2400.00,2500.00,2500.00,2600.00,2600.00,2595.00,2550.00,2505.00,2543.00,2550.00,2500.00,2500.00,2600.00,2600.00,2650.00,2700.00,2650.00,2665.00,2703.00,2682.00,2500.00,2406.50,2400.00,2600.00,2650.00,2700.00,2685.50,2700.00,2622.50,2700.00,2700.00,2800.00,2700.00,2700.00,2795.00,2869.50
1,Chicago,Cook County,Chicago-Naperville-Elgin,60657,IL,2,0,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,895.00,850.00,845.00,875.00,885.00,895.00,900.00,875.00,875.00,915.00,950.00,905.00,950.00,950.00,925.00,925.00,925.00,925.00,950.00,985.00,985.00,985.00,975.00,980.00,975.00,995.00,975.00,960.00,977.50,975.00,975.00,975.00,965.00,1020.00,1000.00,995.00,1050.00,1050.00,1010.00,1005.00,1020.00,1020.00,1022.50,998.00,1075.00,1075.00,1050.00,1080.00,1095.00,1095.00,1125.00,1115.00,1095.00,1075.00,1075.00,1055.00,1070.00,1075.00,1075.00,1070.00,1150.00,1150.00,1150.00,1122.50,1150.00,1140.00,1130.00,1107.00,1100.00,1095.00,1095.00,1085.00,1150.00,1150.00,1145.00,1140.00,1142.50,1145.00,1125.00,1095.00,1050.00,1050.00,1030.00,1055.00,1127.50,1100.00,1195.00,1195.00,1165.00,1145.00,1150.00,1171.50,1150.00,1125.00,1120.00
2,New York,New York County,New York-Newark-Jersey City,10023,NY,3,0,nan,nan,nan,nan,nan,nan,nan,nan,nan,3400.00,2897.50,2447.50,2350.00,2350.00,2400.00,2500.00,2397.50,2350.00,2400.00,2300.00,2295.00,2200.00,2295.00,2295.00,2200.00,2235.00,2250.00,2240.00,2280.00,2299.00,2300.00,2350.00,2322.50,2300.00,2250.00,2200.00,2200.00,2210.00,2220.00,2300.00,2240.00,2270.00,2350.00,2300.00,2300.00,2365.00,2350.00,2395.00,2385.00,2330.00,2300.00,2400.00,2650.00,2675.00,2750.00,2800.00,2700.00,2700.00,2765.00,2750.00,2800.00,2875.00,2925.00,2900.00,2825.00,2768.00,2905.00,2897.50,2910.00,2850.00,2896.50,2900.00,2900.00,2884.00,2750.00,2720.00,2850.00,2652.00,2615.00,2695.00,2662.50,2600.00,2800.00,2850.00,2800.00,2800.00,2800.00,2750.00,2819.00,2760.00,2750.00,2765.00,2795.00,2800.00,2893.00,2897.50,2800.00,2800.00,2872.50,2800.00,2795.00,2700.00,2700.00,2790.00,2762.50,2787.50,2750.00,2800.00,2780.00,2800.00,2862.50,2700.00,2700.00,2755.00,2800.00,2800.00,2850.00
3,Chicago,Cook County,Chicago-Naperville-Elgin,60614,IL,4,0,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1550.00,1527.50,1550.00,1527.50,1275.00,1350.00,1325.00,1397.50,1265.00,1340.00,1427.50,1500.00,1500.00,1467.00,1468.50,1469.00,1350.00,1300.00,1275.00,1250.00,1242.50,1205.00,1320.00,1300.00,1352.50,1347.50,1400.00,1390.00,1350.00,1345.00,1255.00,1250.00,1303.50,1360.00,1395.00,1405.00,1457.50,1450.00,1445.00,1399.00,1350.00,1342.00,1295.00,1295.00,1250.00,1255.00,1255.00,1285.00,1250.00,1285.00,1375.00,1300.00,1395.00,1361.00,1350.00,1320.00,1325.00,1325.00,1350.00,1320.00,1350.00
4,El Paso,El Paso County,El Paso,79936,TX,5,0,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,1000.00,995.00,962.50,950.00,995.00,1000.00,1075.00,1037.50,1050.00,1050.00,995.00,1050.00,1075.00,1025.00,1000.00,1000.00,1000.00,995.00,985.00,985.00,975.00,975.00,950.00,950.00,967.50,960.00,950.00,950.00,950.00,995.00,975.00,975.00,950.00,950.00,995.00,995.00,995.00,1000.00,995.00,975.00,995.00,975.00,950.00,950.00,950.00,975.00,995.00,1000.00,1000.00,1012.50,1000.00,1000.00,1000.00,995.00,1000.00,995.00,1000.00,1000.00,975.00,995.00,950.00,982.50,975.00,985.00,975.00,975.00,975.00,970.00,1000.00,995.00,995.00,995.00,995.00,995.00,975.00,995.00,985.00,995.00,995.00,995.00,1050.00,1035.00,1050.00,1045.00,1000.00,1050.00,1050.00,1050.00,1050.00,1050.00,1000.00,995.00,1012.50,1000.00,1070.00,1100.00,1100.00,1100.00,1100.00,1085.00,1050.00

In [33]:
#View zillow data types
print('Original Zillow data types: \n', zillow.dtypes)

Original Zillow data types:
 City         object
County       object
Metro        object
Zip          object
State        object
SizeRank     object
Bedrooms     object
2010-03     float64
2010-04     float64
2010-05     float64
2010-06     float64
2010-07     float64
2010-08     float64
2010-09     float64
2010-10     float64
2010-11     float64
2010-12     float64
2011-01     float64
2011-02     float64
2011-03     float64
2011-04     float64
2011-05     float64
2011-06     float64
2011-07     float64
2011-08     float64
2011-09     float64
2011-10     float64
2011-11     float64
2011-12     float64
2012-01     float64
2012-02     float64
2012-03     float64
2012-04     float64
2012-05     float64
2012-06     float64
2012-07     float64
2012-08     float64
2012-09     float64
2012-10     float64
2012-11     float64
2012-12     float64
2013-01     float64
2013-02     float64
2013-03     float64
2013-04     float64
2013-05     float64
2013-06     float64
2013-07     float64
2013-08     float64
2013-09     float64
2013-10     float64
2013-11     float64
2013-12     float64
2014-01     float64
2014-02     float64
2014-03     float64
2014-04     float64
2014-05     float64
2014-06     float64
2014-07     float64
2014-08     float64
2014-09     float64
2014-10     float64
2014-11     float64
2014-12     float64
2015-01     float64
2015-02     float64
2015-03     float64
2015-04     float64
2015-05     float64
2015-06     float64
2015-07     float64
2015-08     float64
2015-09     float64
2015-10     float64
2015-11     float64
2015-12     float64
2016-01     float64
2016-02     float64
2016-03     float64
2016-04     float64
2016-05     float64
2016-06     float64
2016-07     float64
2016-08     float64
2016-09     float64
2016-10     float64
2016-11     float64
2016-12     float64
2017-01     float64
2017-02     float64
2017-03     float64
2017-04     float64
2017-05     float64
2017-06     float64
2017-07     float64
2017-08     float64
2017-09     float64
2017-10     float64
2017-11     float64
2017-12     float64
2018-01     float64
2018-02     float64
2018-03     float64
2018-04     float64
2018-05     float64
2018-06     float64
2018-07     float64
2018-08     float64
2018-09     float64
2018-10     float64
2018-11     float64
2018-12     float64
2019-01     float64
2019-02     float64
2019-03     float64
2019-04     float64
2019-05     float64
2019-06     float64
2019-07     float64
2019-08     float64
2019-09     float64
2019-10     float64
2019-11     float64
dtype: object

# Data Cleaning

## Convert zillow data into a tidy dataset

In [34]:
#Set columns for melt
id_vars = list(zillow.loc[:,:'Bedrooms'].columns.values)
value_vars = list(zillow.iloc[:,7:].columns.values)

#Melt zillow. Create a Data and Price/SqrFt column
zillow = zillow.melt(id_vars= id_vars,value_vars= value_vars, var_name='Date', value_name= 'Median_Rent' )

#Check
print('Updated Zillow data shape:',zillow.shape)
display(zillow.head())

Updated Zillow data shape: (753480, 9)

,City,County,Metro,Zip,State,SizeRank,Bedrooms,Date,Median_Rent
0,New York,New York County,New York-Newark-Jersey City,10025,NY,1,0,2010-03,nan
1,Chicago,Cook County,Chicago-Naperville-Elgin,60657,IL,2,0,2010-03,nan
2,New York,New York County,New York-Newark-Jersey City,10023,NY,3,0,2010-03,nan
3,Chicago,Cook County,Chicago-Naperville-Elgin,60614,IL,4,0,2010-03,nan
4,El Paso,El Paso County,El Paso,79936,TX,5,0,2010-03,nan

In [35]:
#Print updateddata types
print('Updated Zillow data types: \n', zillow.dtypes)

Updated Zillow data types:
 City            object
County          object
Metro           object
Zip             object
State           object
SizeRank        object
Bedrooms        object
Date            object
Median_Rent    float64
dtype: object

## Remove missing Median_Rent values

Need these values to make comparisons in later analysis to compare median rent in San Francisco to Airbnb rent

In [36]:
#Removing rows where Median_Rent is null
zillow = zillow[-zillow.Median_Rent.isnull()]

#Print updated shape
print('Updated zillow data shape:',zillow.shape)

#Preview updated data
display(zillow.head())

Updated zillow data shape: (277104, 9)

,City,County,Metro,Zip,State,SizeRank,Bedrooms,Date,Median_Rent
4928,Virginia Beach,Virginia Beach City,Virginia Beach-Norfolk-Newport News,23462,VA,83,3,2010-03,1200.00
11368,Virginia Beach,Virginia Beach City,Virginia Beach-Norfolk-Newport News,23462,VA,83,3,2010-04,1250.00
17808,Virginia Beach,Virginia Beach City,Virginia Beach-Norfolk-Newport News,23462,VA,83,3,2010-05,1200.00
24248,Virginia Beach,Virginia Beach City,Virginia Beach-Norfolk-Newport News,23462,VA,83,3,2010-06,1250.00
30688,Virginia Beach,Virginia Beach City,Virginia Beach-Norfolk-Newport News,23462,VA,83,3,2010-07,1225.00

## Column specific cleaning**

In [37]:
#Remove 'County' from County
zillow.County = zillow.County.str.replace('County','', regex=True)

# Export Cleaned Data

In [38]:
#Set path to export cleaned zillow data
path = r'C:\Users\kishe\Documents\Data Science\Projects\Python Projects\In Progress\Air BnB - SF\Data\02_Intermediate\2020_0130_Zillow_Cleaned.csv'

#Write file
zillow.to_csv(path, sep=',')